# Generated by Django 4.1.4 on 2022-12-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='unit',
            field=models.CharField(choices=[('UNITE', 'UNITE'), ('KG', 'KG'), ('L', 'L'), ('SAC', 'SAC'), ('BIDOU', 'BIDOU')], default='UNITE', max_length=10),
        ),
    ]
