# Generated by Django 4.1.4 on 2022-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0002_article_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tva',
            field=models.FloatField(default=0, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='article',
            name='unit',
            field=models.CharField(choices=[('UNITE', 'UNITE'), ('KG', 'KG'), ('G', 'G'), ('L', 'L'), ('SAC', 'SAC'), ('BOUTEILLE', 'BOUTEILLE'), ('CARTON', 'CARTON')], default='UNITE', max_length=10),
        ),
    ]
